name: Build Lightweight Flutter APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# 🌟 إعطاء صلاحيات كاملة عشان نتجاوز قفل GitHub (خطأ 128)
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean & Get Packages
        run: |
          flutter clean
          flutter pub get

      # 🌟 أمر البناء السحري اللي بيقسم التطبيق ويطلع لك النسخة الخفيفة
      - name: Build Split APK
        run: flutter build apk --release --split-per-abi

      # 🌟 رفع النسخة الخفيفة المخصصة للجوالات الحديثة عشان تحملها
      - name: Upload Lightweight APK
        uses: actions/upload-artifact@v4
        with:
          name: Tijarati-Pro-Light-APK
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk