name: Build Flutter APK

on:
  workflow_dispatch:

# 🌟 هذا هو المفتاح السحري اللي بيعطي المصنع صلاحيات "مدير" غصب عن نظام الحماية
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 🌟 سحب الكود بتجاوز القفل الأمني
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean & Get Packages
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tijarati-Pro-APK
          path: build/app/outputs/flutter-apk/app-release.apk