name: Build Flutter APK

on:
  workflow_dispatch:

# 🌟 هذا هو المفتاح السحري اللي بيقتل خطأ 128 للأبد 
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 🌟 سحب كل الملفات بدون استثناءات أمنية

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tijarati-Pro-APK
          path: build/app/outputs/flutter-apk/app-release.apk