name: Build Flutter APK

on:
  workflow_dispatch: # زر التشغيل اليدوي
  push:
    branches:
      - main
      - master

# إعطاء الصلاحيات كاملة عشان ما يطلع لنا خطأ 128
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # إعداد الجافا (الإصدار 17 هو المتوافق مع فلاتر الجديد)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # إعداد بيئة فلاتر
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # تنظيف المشروع من أي مخلفات قديمة قبل البناء
      - name: Clean & Get Packages
        run: |
          flutter clean
          flutter pub get

      # بناء التطبيق النهائي
      - name: Build APK
        run: flutter build apk --release

      # رفع ملف التطبيق عشان تحمله
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tijarati-Pro-APK
          path: build/app/outputs/flutter-apk/app-release.apk