name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 جلب كود المشروع
        uses: actions/checkout@v4

      - name: ☕ تجهيز الجافا
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🦋 تجهيز فلاتر
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 📦 تحميل المكتبات
        run: flutter pub get

      - name: 🔨 بناء التطبيق (النسخة المصغرة)
        run: flutter build apk --split-per-abi

      - name: 📤 رفع ملف التطبيق الجاهز
        uses: actions/upload-artifact@v4
        with:
          name: Tijarati-Pro-APK
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk